version: '3'

volumes: 
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    # The official v3 Traefik docker image
    image: "traefik:v2.5"
    # Enables the web UI and tells Traefik to listen to docker
    networks:
      - traefik-network
    container_name: "traefik"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - ./etc/traefik:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  multi-color-button:
    image: "nginx:latest"
    networks:
    - traefik-network
    container_name: "multi-color-button"
    volumes: 
      - ./myAplication:/usr/share/nginx/html
    labels: 
    - "traefik.enable=true"
    - "traefik.http.routers.multi-color-button.rule=Host(`localhost`)"
    - "traefik.http.routers.multi-color-button.entrypoints=web"
    - "traefik.http.services.multi-color-button.loadbalancer.server.port=80"
      
networks:
  traefik-network:
    driver: bridge












